name: 'ReSpec W3C Auto-Publish'
author: 'Sid Vishnoi'
description: 'Validate ReSpec based specs and publish to /TR/'
inputs:
  ECHIDNA_TOKEN:
    description: 'Echidna token'
    required: true
  GH_USER:
    description: 'GitHub user login. Used with respec-validator for API request quota limits.'
    required: false
  GH_TOKEN:
    description: 'GitHub user personal token. Used with respec-validator for API request quota limits.'
    required: false
  ECHIDNA_MANIFEST_URL:
    description: 'TR Manfiest URL. Example: https://w3c.github.io/gamepad/W3CTRMANIFEST'
    required: true
  WG_DECISION_URL:
    description: 'A URL to the working group decision to use auto-publish (usually from a w3c mailing list).'
    required: true
  CC:
    description: "Comma separated list of email addresses to CC to."
    required: true
runs:
  using: 'node12'
  main: 'index.js'
