name: 'ReSpec W3C Auto-Publish'
author: 'Sid Vishnoi'
description: 'Validate ReSpec based specs and publish to /TR/'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  ECHIDNA_TOKEN:
    description: 'Echidna token'
    required: true
  ECHIDNA_MANIFEST_URL:
    description: 'TR Manfiest URL. Example: https://w3c.github.io/gamepad/W3CTRMANIFEST'
    required: true
  WG_DECISION_URL:
    description: 'A URL to the working group decision to use auto-publish (usually from a w3c mailing list).'
    required: true
  CC:
    description: "Comma separated list of email addresses to CC to."
    required: true
  INPUT_FILE:
    description: 'Input HTML file path, relative to repository root.'
    required: false
    default: 'index.html'
  CHECK_LINKS:
    description: 'Validate links and cross references'
    required: false
    default: true
  VALIDATE_MARKUP:
    description: 'Validate HTML markup'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'index.js'
