name: Node CI

on:
  push:
    branches:
      - gh-pages
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v1
      - uses: sidvishnoi/respec-w3c-auto-publish # use the action
        with:
          ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          GH_USER: ${{ secrets.GH_USER }}     # optional
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # optional
          URL: "https://w3c.github.io/gamepad/W3CTRMANIFEST"
          DECISION: "https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
          CC: "someone@somewhere.com"
